### ISSUE TITLE
Some icons not fetching

### ISSUE THREAD

**Issue by tynanpurdy** [LitoMore/simple-icons-framer#1]
Hi! I am using this component in my Framer site for socials navigation. I am having trouble accessing the Bluesky icon. It does not surface in the selection list within Framer. 

<img width="174" alt="image" src="https://github.com/user-attachments/assets/16c6ed50-98d2-479f-a0d2-4e1fafe2ef1d">

I have confirmed that `bluesky` is available from simple-icons (see https://cdn.simpleicons.org/bluesky). I have specified a specific distribution version from jsDelivr which I confirmed has the bluesky icon (13.19.0) as well. With any of those sources, I get a default icon when changing the default on line `86` rather than the Bluesky icon. 

I am not sure how many icons are affected by this issue, but `bluesound` seems to be one of them.
Any idea how I can access all of the simple-icons in the latest release from Framer?

**Comment by LitoMore** [comment]
Hi @tynanpurdy, thanks for reporting. The source has been outdated for a while.

The root cause is Framer cached those dependencies from the source file. I just force-updated the build:

```
https://framer.com/m/SimpleIcons-1Tar.js
```

Can you refresh and try again?

I will also consider refactoring the code to fetch the icon list dynamically so that the Framer cache won't mess these up.

**Comment by LitoMore** [comment]
Close as resolved.
